spring:
  application:
    name: hertz

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hertz?serverTimezone=UTC&characterEncoding=UTF-8
    username: 'root'
    password: 'gnpp'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
jwt:
  access-token-secret: '660a9e8ca6206bb3ce4750335ef6b42148dd3101af88d10ea9b338432fb4d867'
  refresh-token-secret: '03682213a08cd5b4406bc3f20f8b623efb7f6f55779d31ad7eb13292ac017d81'
