spring:
  application:
    name: hertz

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hertz?serverTimezone=UTC&characterEncoding=UTF-8
    username: 'root'
    password: 'gnpp'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
